// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.isPlayable = true;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
      return setTimeout(((function(_this) {
        return function() {
          if (_this.handScore() === 21) {
            return _this.trigger('blackjack', _this);
          }
        };
      })(this)), 50);
    };

    Hand.prototype.isBusted = function() {
      if (this.handScore() > 21) {
        this.isPlayable = false;
        return true;
      }
      return false;
    };

    Hand.prototype.handScore = function() {
      if ((this.scores()[1] != null) && this.scores()[1] <= 21) {
        return this.scores()[1];
      } else {
        return this.scores()[0];
      }
    };

    Hand.prototype.hit = function() {
      var hitCard;
      if (this.isPlayable) {
        hitCard = this.add(this.deck.pop()).last();
        if (this.isBusted()) {
          this.trigger('turnEnded', this);
        }
        return hitCard;
      }
    };

    Hand.prototype.stand = function() {
      if (this.isPlayable) {
        this.trigger('turnEnded', this);
        return this.isPlayable = false;
      }
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.playHand = function() {
      this.unflip();
      while (this.handScore() < 17 && !this.isBusted()) {
        this.hit();
      }
      return this.trigger('turnEnded', this);
    };

    Hand.prototype.unflip = function() {
      this.each(function(card) {
        if (!card.get('revealed')) {
          return card.flip();
        }
      });
      if (this.handScore() === 21) {
        return this.trigger('blackjack', this);
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
